### ISSUE TITLE
kok 台服的问题

### ISSUE THREAD

**Issue by qiqimutou** [28598519a/KoK_AssetDecDL#2]
大佬，kok的台服你有拆过吗，我拆了几天，提取不动url，台服比nukuta的更新快点，steam的资源最全就是落后版本，你能说说怎么拆安卓端的url吗 实在搞不定 各种方法都试了 一抓包就没网络

**Comment by 28598519a** [comment]
我之前是抓包，台服不知道，但應該也能抓，nutaku的我當初整的時候是用Android版的

**Comment by 28598519a** [comment]
基本上抓包就2種結果，一種是封包不給轉發，沒抓到包但能進遊戲，另一種自然就是有轉發成功，抓到包，也能進遊戲
另外，可能要確認一下進抓包後，Android中開瀏覽器之類的能不能上、能不能抓得到瀏覽器的包，如果不行那就是封包轉發設定的問題
