### ISSUE TITLE
大佬 樱境物语有兴趣吗？

### ISSUE THREAD

**Issue by qiqimutou** [28598519a/KoK_AssetDecDL#3]
我搞到了游戏的资源列表，但是他u3d搞了点东西，让AssetStudio打不开，我有旧版文件，我对比了下只修改了几个字节，这是旧版文件里面也有新版的文件
网页版地址：https://www.ero-labs.com/zh/game.html?id=27
[https://drive.google.com/file/d/1x1bxRh8VyzXL6HMIwUSB4IGL00IFEDxm/view?usp=share_link](url)

**Comment by 28598519a** [comment]
今天有空順便看了一下，你貼的版本好處理，直接把2018.3.5f1跟後一位替換成2020.3.41f1就能讀
但我剛才看了一下現在的版本搞東西的法又改了
![](https://github.com/28598519a/KoK_AssetDecDL/assets/33422418/744b04e8-b6bc-46bc-af4f-b0a6fbab89fb)

**Comment by 28598519a** [comment]
笑死，還真的是，直接把0x24 + 0xF就成了

**Comment by 28598519a** [comment]
> 我搞到了游戏的资源列表，但是他u3d搞了点东西，让AssetStudio打不开，我有旧版文件，我对比了下只修改了几个字节，这是旧版文件里面也有新版的文件 网页版地址：https://www.ero-labs.com/zh/game.html?id=27 [https://drive.google.com/file/d/1x1bxRh8VyzXL6HMIwUSB4IGL00IFEDxm/view?usp=share_link](url)

今天有空順便看了一下，你貼的版本好處理，直接把2018.3.5f1跟後一位替換成2020.3.41f1就能讀

**Comment by 28598519a** [comment]
重新看了一下，經過實際嘗試，剛才的判斷有誤，比對了多個new/old文件後，發現0x3FB的位置有被動過，後面的順序不一定，但一個文件總共會被修改6個位置

---

具體來說取決於檔案大小，以下是一些例子:
3FB C68 D99 184B 197C 21E0
3FB D99 197C 37C1 43A4 4D42 (End: 513C)
3FB D99 197C 51FC 5DDF 677D (End: 6B77)
3FB D99 197C 94D9 A0BC AA5A (End: AE54)
3FB D99 197C D13D0 7EFB3 7F951
3FB D99 197C 2FCD32 2FD915 2FE2B3 (End: 2FE6AD)
3FB D99 197C 176B9B 17777E 17811C
3FB D99 197C 9B1457 9B203A 9B29D8 (End: 9B2DD2)

**Comment by 28598519a** [comment]
AssetBundleLoader__LoadFromFile
![](https://github.com/28598519a/KoK_AssetDecDL/assets/33422418/baea97ca-624c-4cc0-b8f7-3b105b446493)
大概就是那個ChangeIdx函數在處理，但我libil2cpp.so是dump解密出來的，導致IDA分析的結果，邏輯變很亂也有些問題，所以不是很想搞

**Comment by 28598519a** [comment]
最後還是搞好了，這是程式 下載+解密
[CherryTale_AssetDecDL](https://github.com/28598519a/CherryTale_AssetDecDL)
