### ISSUE TITLE
星神少女

### ISSUE THREAD

**Issue by qiqimutou** [28598519a/KoK_AssetDecDL#5]
游戏下载地址
[https://n.holesg.xyz/?attributionId=0](url)

资源更新地址
[https://rp-cn-prod-server.rpfans.net/api/game-data/hash/latest](url)
[https://rp-cn-prod-server.rpfans.net/api/game-data/hash/request/latest](url)
压缩包解压密码是:test

他的加密和kok类似

**Comment by 28598519a** [comment]
https://v.opgaming.xyz/

看來是同一間出的，我之後有空會研究一下

話說資源地址給個範例吧 (隨便個zip包的就行)，我先稍微看個幾眼

**Comment by qiqimutou** [comment]
> https://v.opgaming.xyz/
> 
> 看來是同一間出的，我之後有空會研究一下
> 
> 話說資源地址給個範例吧 (隨便個zip包的就行)，我先稍微看個幾眼

https://d2o6bt848m9g7d.cloudfront.net/ + 资源列表的url项 
下载方法就这样
https://d2o6bt848m9g7d.cloudfront.net/OnRequestAssets/SpinesZip/Heros_1405_HeroBG1405_Lv2_943dd8ce96a772e7a32b1e69f33d21bcb1d2dfd7bee209b3265ceed606930cfc.zip
