### ISSUE TITLE
大佬可以看一下星神少女吗？

### ISSUE THREAD

**Issue by s120900225** [28598519a/KoK_AssetDecDL#6]
我看了一眼里面的加密是跟逆王传说是一样的加密，但是算法好像是一样的，key不一样
![image](https://github.com/28598519a/KoK_AssetDecDL/assets/81162564/c957f52c-52dc-486d-adf9-221328c23c65)
https://n.holesg.xyz/?attributionId=1

**Comment by 28598519a** [comment]
[Aeon_AssetDecDL](https://github.com/28598519a/Aeon_AssetDecDL)

**Comment by s120900225** [comment]
感谢大佬
