### ISSUE TITLE
星之守护

### ISSUE THREAD

**Issue by qiqimutou** [28598519a/KoK_AssetDecDL#7]
https://www.365h.today/game/detail/14493?referrer=singular_click_id%3D0990efe3-312a-426e-a9d6-a2b3a1fd93ad&utm_source=sm501
这游戏是c2d引擎资源基本都在apk，更新是zip
http://data2.nlphebei.com/h365/android/url_config.lua
你能找到这游戏的文件列表吗？我把res 和 src的文件夹里的文件都翻烂了都没看到原名

**Comment by qiqimutou** [comment]
<pre>
import os
import zipfile

def bao_cun_er_jin_zhi_wen_jian(sj, wj):
    with open(wj, 'wb') as xa:
        xa.write(bytes(sj))

def duo_zi_jie_xor_shu_ju(sj, my):
    return [xb ^ my[xa % len(my)] for xa, xb in enumerate(sj)]

def chuang_jian_wen_jian_jia(ml):
    if not os.path.exists(ml):
        os.makedirs(ml)

def c2d_apk_dao_chu_chai_fen(wj):
    with zipfile.ZipFile(wj, 'r') as xa:
        la = [xb for xb in xa.namelist() if xb.lower().endswith('.g')]
        for xc in la:
            with xa.open(xc) as xd:
                sj = xd.read()
            chuang_jian_wen_jian_jia(os.path.dirname(xc))
            if sj[:9] == b'\x3F\x42\x60\x6F\x5F\x44\x67\x5C\x5E':
                dc = duo_zi_jie_xor_shu_ju(bytearray(sj[9:]), [0x30, 0x78, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30])
                if dc[:4] == [137, 80, 78, 71]:
                    hz = 'png'
                elif dc[:1] == [10]:
                    hz = 'atlas'
                elif dc[:4] == [67, 67, 90, 33]:
                    hz = 'pvr.ccz'
                elif dc[:3] == [255, 216, 255]:
                    hz = 'jpg'
                elif dc[:5] == [60, 63, 120, 109, 108]:
                    hz = 'plist'
                elif dc[:1] == [28]:
                    hz = 'skel'
                elif dc[:4] == [123, 34, 115, 107]:
                    hz = 'json'
                else:
                    hz = 'g'
            else:
                dc = sj
                if dc[:4] == b'\x89\x50\x4E\x47':
                    hz = 'png'
                elif dc[:1] == b'\x0A':
                    hz = 'atlas'
                elif dc[:4] == b'\x43\x43\x5A\x21':
                    hz = 'pvr.ccz'
                elif dc[:3] == b'\xFF\xD8\xFF':
                    hz = 'jpg'
                elif dc[:4] == b'\x3C\x3F\x78\x6D':
                    hz = 'plist'
                elif dc[:1] == b'\x1C':
                    hz = 'skel'
                elif dc[:8] == b'\x7B\x22\x73\x6B\x65\x6C\x65\x74':
                    hz = 'json'
                elif dc[:4] == b'\x14\x00\x00\x00':
                    hz = 'zz'
                else:
                    hz = 'g'
            bao_cun_er_jin_zhi_wen_jian(dc, f"{xc[:-1]}{hz}")

c2d_apk_dao_chu_chai_fen('星之守护.apk')
</pre>
解密脚本，因为我找不到文件名没办法只能根据标头设置后缀导出，但是这游戏的贴图尺寸都是常规1024这种 太难找对应的atlas和skel了

**Comment by 28598519a** [comment]
看你寫python解密腳本覺得蠻神奇的，像我都是逆出C++後就直接老實照抄，蠻好奇你都怎麼搞得?

先跟你說一下，最近沒啥時間整新游，估計至少11月以後才會繼續動新的了，而且到時我打算先搞 放置少女跟星神少女。

**Comment by 28598519a** [comment]
看你寫python解密腳本覺得蠻神奇的，像我都是逆出C++後就直接老實照抄，蠻好奇你都怎麼搞得?

先跟你說一下，最近沒啥時間整新游，估計最快11月以後才會繼續動新的了，而且到時我打算先搞 放置少女跟星神少女。
然後我對這種還原檔名的其實不太擅長，我隨便舉2個例子 [AGUDecoder](https://github.com/28598519a/AGUDecoder)、[Kanojo](https://github.com/28598519a/Kanojo_AssetDecDL) 我到現在都沒解決，尤其是cocos2d這種有些東西寫在c++，有些在lua的找起來更是麻煩。

**Comment by qiqimutou** [comment]
>

**Comment by qiqimutou** [comment]
> 看你写的python解密脚本觉得相当神奇的，像我都是逆出C++后就直接老实照抄，相当好奇你都怎么搞得？
> 
> 先茹说一下，最近没啥时间整新游，估计最快11个月以后才会继续动新的了，而且到时候我打算先搞一下放置少女跟星神少女。然后我对这个还原档 名其实不太擅长，我随便举了2个例子[AGUDecoder](https://github.com/28598519a/AGUDecoder)、[Kanojo](https://github.com/28598519a/Kanojo_AssetDecDL)我现在都没有解决，尤其是cocos2d这种有些东西是用c++写的，有些在lua的找起来就更加麻烦了。

我是直接看文件的hex,研究下规律,研究不出来就放弃，xor的话如果不是只有一小段的话， 我还是能猜出来秘钥的，Kanojo的还原名字挺简单的
ae9247d1-3d69-134e-7b7c-a8efcb77f9ed	629958	3bbc87212f4a2397db7992297d4696a6	-1	629734	protector.dat
先下载这个文件解密后
然后再下载资源文件，解压的时候根据路径名导出修改成原名
1.atlas	6a85f4b6-02b9-c286-bf32-74c1835e7617/4bd42639-eeb2-72d1-2370-e69badf28083/3c6a7c80-015a-c1ba-2169-ba570a5e07e1/8ff56a66-4d8c-8ffb-9aea-5df4aeb143d6/47319e0f-e53a-0ab2-2707-b07766c443fc/8d7f802f-32fb-2bcc-836e-3226e4c0a7ef

**Comment by qiqimutou** [comment]
c2d 还原名字 我还是挺擅长的，主要一般都有表，不过没表也有做法，像有import这个文件夹的，可以靠解析json的uuid得到文件原名
但是这星之守护毛都没有，lua里也没看到文件id这些东西

**Comment by qiqimutou** [comment]
<pre>
import json
import os

def base64_to_uuid(base64):
    BASE64_VALUES = [64] * 123
    BASE64_KEYS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='

    for i, c in enumerate(BASE64_KEYS):
        BASE64_VALUES[ord(c)] = i

    HEX_CHARS = list('0123456789abcdef')
    _template = ['', '', '', '']
    UUID_TEMPLATE = _template + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + _template + _template
    INDICES = [i for i, x in enumerate(UUID_TEMPLATE) if x != '-']
    
    def decode_uuid(base64):
        if len(base64) != 22:
            return base64

        UUID_TEMPLATE[0] = base64[0]
        UUID_TEMPLATE[1] = base64[1]

        j = 2
        for i in range(2, 22, 2):
            lhs = BASE64_VALUES[ord(base64[i])]
            rhs = BASE64_VALUES[ord(base64[i + 1])]
            UUID_TEMPLATE[INDICES[j]] = HEX_CHARS[lhs >> 2]
            UUID_TEMPLATE[INDICES[j + 1]] = HEX_CHARS[((lhs & 3) << 2) | (rhs >> 4)]
            UUID_TEMPLATE[INDICES[j + 2]] = HEX_CHARS[rhs & 0xF]
            j += 3

        return ''.join(UUID_TEMPLATE)

    return decode_uuid(base64)

wj = 'config.d5e28.json'
za = '放置少女列表_旧.txt'
zb = '放置少女列表_新.txt'
zc = '放置少女_更新列表.txt'
if os.path.exists(za) and os.path.exists(zb):
    os.remove(za)
if os.path.exists(zb):
    os.rename(zb, za)
with open(wj, 'r', encoding='utf-8') as f:
    js = json.load(f)
#获取文件名
la = {xa: js['paths'][xa][0] for xa in js['paths']}
lc = {xa: js['paths'][xa][-1] for xa in js['paths']}
#转换uuid
lb = {}
j = -1
for xb in js['uuids']:
    j += 1
    lb.update({j: base64_to_uuid(xb)})
#获取哈希值
dc = []
for xc in range(1,3):
    j = 0
    if xc == 1:
        mo = 'native'
    else:
        mo = 'import'
    for xd in js['versions'][mo]:
        j += 1
        if j % 2 == 0:
            y = xd
            if str(x) in la:
                c1 = la[str(x)]
                c1 = c1.replace("/", "\\")
                c2 = lb[x]
                c3 = lc[str(x)]
                if str(c3) == '0':
                    if c1[:5] == 'spine':
                        hz1 = '.atlas'
                    else:
                        hz1 = '.moc3'
                    hz2 = hz1
                elif str(c3) == '1':
                    hz1 = '.png'
                    hz2 = hz1
                elif str(c3) == '2':
                    hz1 = '.json'
                    hz2 = hz1
                elif str(c3) == '3':
                    hz1 = '.json'
                    hz2 = hz1
                elif str(c3) == '4':
                    hz1 = '.bin'
                    hz2 = '.skel'
                if xc == 1:
                    c3 = "{}/{}/{}.{}{}<{}{}".format(mo, c2[0:2], c2, y, hz1, c1, hz2)
                else:
                    c3 = "{}/{}/{}.{}.json<{}.json".format(mo, c2[0:2], c2, y, c1)
                dc.append(c3)
            else:
                print(x)
        else:
            x = xd
with open(zb, "w") as f:
    f.write("\n".join(dc))
if os.path.exists(za) and os.path.exists(zb):
    with open(za, 'r') as xe, open(zb, 'r') as xf:
        tx1 = set(xe.readlines())
        tx2 = set(xf.readlines())
    db = sorted(tx2 - tx1)
    with open(zc, "w") as f:
        f.write("\n".join(line.strip() for line in db))
else:
    with open(zc, "w") as f:
        f.write("\n".join(dc))
</pre>
放置少女网页版下载资源的方法
uuid转换我抄的c2d代码
放置少女的json挺好解析的，判断后缀我是靠config.json里的types项 按照路径后面的数字判断，实测我这个方法没有问题，资源基本下全了，每次下载和旧版的表做对比生成需要更新的表，这样就可以只下载新增的文件
不过我不知道怎么下载这个json，我都是打开网页版抓包拿到的json
我是只下了立绘的json文件 Character/config
根据config下载的链接得到下载前缀"https://snh5-cdn1.ttagj.com/game/release/assets/Character/"

**Comment by qiqimutou** [comment]
> import json
> import os
> 
> def base64_to_uuid(base64):
>     BASE64_VALUES = [64] * 123
>     BASE64_KEYS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
> 
>     for i, c in enumerate(BASE64_KEYS):
>         BASE64_VALUES[ord(c)] = i
> 
>     HEX_CHARS = list('0123456789abcdef')
>     _template = ['', '', '', '']
>     UUID_TEMPLATE = _template + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + _template + _template
>     INDICES = [i for i, x in enumerate(UUID_TEMPLATE) if x != '-']
>     
>     def decode_uuid(base64):
>         if len(base64) != 22:
>             return base64
> 
>         UUID_TEMPLATE[0] = base64[0]
>         UUID_TEMPLATE[1] = base64[1]
> 
>         j = 2
>         for i in range(2, 22, 2):
>             lhs = BASE64_VALUES[ord(base64[i])]
>             rhs = BASE64_VALUES[ord(base64[i + 1])]
>             UUID_TEMPLATE[INDICES[j]] = HEX_CHARS[lhs >> 2]
>             UUID_TEMPLATE[INDICES[j + 1]] = HEX_CHARS[((lhs & 3) << 2) | (rhs >> 4)]
>             UUID_TEMPLATE[INDICES[j + 2]] = HEX_CHARS[rhs & 0xF]
>             j += 3
> 
>         return ''.join(UUID_TEMPLATE)
> 
>     return decode_uuid(base64)
> 
> wj = 'config.d5e28.json'
> za = '放置少女列表_旧.txt'
> zb = '放置少女列表_新.txt'
> zc = '放置少女_更新列表.txt'
> if os.path.exists(za) and os.path.exists(zb):
>     os.remove(za)
> if os.path.exists(zb):
>     os.rename(zb, za)
> with open(wj, 'r', encoding='utf-8') as f:
>     js = json.load(f)
> #获取文件名
> la = {xa: js['paths'][xa][0] for xa in js['paths']}
> lc = {xa: js['paths'][xa][-1] for xa in js['paths']}
> #转换uuid
> lb = {}
> j = -1
> for xb in js['uuids']:
>     j += 1
>     lb.update({j: base64_to_uuid(xb)})
> #获取md5值
> dc = []
> for xc in range(1,3):
>     j = 0
>     if xc == 1:
>         mo = 'native'
>     else:
>         mo = 'import'
>     for xd in js['versions'][mo]:
>         j += 1
>         if j % 2 == 0:
>             y = xd
>             if str(x) in la:
>                 c1 = la[str(x)]
>                 c1 = c1.replace("/", "\\")
>                 c2 = lb[x]
>                 c3 = lc[str(x)]
>                 if str(c3) == '0':
>                     if c1[:5] == 'spine':
>                         hz1 = '.atlas'
>                     else:
>                         hz1 = '.moc3'
>                     hz2 = hz1
>                 elif str(c3) == '1':
>                     hz1 = '.png'
>                     hz2 = hz1
>                 elif str(c3) == '2':
>                     hz1 = '.json'
>                     hz2 = hz1
>                 elif str(c3) == '3':
>                     hz1 = '.json'
>                     hz2 = hz1
>                 elif str(c3) == '4':
>                     hz1 = '.bin'
>                     hz2 = '.skel'
>                 if xc == 1:
>                     c3 = "{}/{}/{}.{}{}<{}{}".format(mo, c2[0:2], c2, y, hz1, c1, hz2)
>                 else:
>                     c3 = "{}/{}/{}.{}.json<{}.json".format(mo, c2[0:2], c2, y, c1)
>                 dc.append(c3)
>             else:
>                 print(x)
>         else:
>             x = xd
> with open(zb, "w") as f:
>     f.write("\n".join(dc))
> if os.path.exists(za) and os.path.exists(zb):
>     with open(za, 'r') as xe, open(zb, 'r') as xf:
>         tx1 = set(xe.readlines())
>         tx2 = set(xf.readlines())
>     db = sorted(tx2 - tx1)
>     with open(zc, "w") as f:
>         f.write("\n".join(line.strip() for line in db))
> else:
>     with open(zc, "w") as f:
>         f.write("\n".join(dc))
> 放置少女网页版下载资源的方法

**Comment by qiqimutou** [comment]
> 看你写的python解密脚本觉得相当神奇的，像我都是逆出C++后就直接老实照抄，相当好奇你都怎么搞得？
> 
> 先茹说一下，最近没啥时间整新游，估计最快11个月以后才会继续动新的了，而且到时候我打算先搞一下放置少女跟星神少女。然后我对这个还原档 名其实不太擅长，我随便举了2个例子[AGUDecoder](https://github.com/28598519a/AGUDecoder)、[Kanojo](https://github.com/28598519a/Kanojo_AssetDecDL)我现在都没有解决，尤其是cocos2d这种有些东西是用c++写的，有些在lua的找起来就更加麻烦了。

**Comment by qiqimutou** [comment]
<pre>
import glob
import os
import zipfile

def chuang_jian_wen_jian_jia(ml):
    if not os.path.exists(ml):
        os.makedirs(ml)

#资源列表表格
wj = 'protector.dat'
#获取当前文件夹所有的zip文件
lb = glob.glob(os.path.join(os.getcwd(), "*.zip"))

def jie_xi_lie_biao_bing_cun_wei_zi_dian(wj):
    with open(wj, "r", encoding="utf8") as xa:
        sj = xa.readlines()
    zd = {}
    for xa in sj:
        #把文件路径做成字典键，原名作为键值
        aa = xa.rstrip("\n").split('\t')
        zd[aa[1]] = aa[0]
    return zd

zd = jie_xi_lie_biao_bing_cun_wei_zi_dian(wj)

for xa in lb:
    with zipfile.ZipFile(xa, 'r') as xb:
        #过滤一遍zip中的文件列表，如果路径名在zd中存在键则导出键值名字，没有就原名
        for xc in xb.namelist():
            if xc in zd:
                dc = f'Asset\\{zd[xc]}'
            else:
                dc = f'Asset\\{xc}'
            chuang_jian_wen_jian_jia(os.path.dirname(dc))
            with xb.open(xc) as xe:
                sj = xe.read()
                with open(dc, 'wb') as xf:
                    xf.write(sj)
</pre>
Kanojo 还原名字的代码 下面是效果图
![6${_Z{~YL6%8X2P)@GB$1}I](https://github.com/28598519a/KoK_AssetDecDL/assets/126901037/6e6cb9ea-01e9-4d07-9e9a-578c976c0c57)

**Comment by 28598519a** [comment]
真的佩服，厲害

**Comment by 28598519a** [comment]
忘記discord怎加了，不過應該是使用者id，就我github名稱，28598...

**Comment by qiqimutou** [comment]
那个姬械联盟我也看了 还原要稍微麻烦点 他那个config 没把立绘的编号原名做进去，需要把apk里的json文件全过一遍找到立绘的id
[1] 是立绘的uuid列表
[5][0][1] 是立绘的名字
[5][0][2] 是atlas的数据
[5][0][3] 是立绘的原名列表
[5][0][4] 是骨骼的json
他用的c2d版本json文件都是列表，判断起来挺逆天的...
![R5HOLFQW@ 5M 10WG2QDGDH](https://github.com/28598519a/KoK_AssetDecDL/assets/126901037/1af21bae-0639-40c7-90bd-a6cd120ecd95)

**Comment by qiqimutou** [comment]
<pre>
import os
import json
import zipfile

def base64_to_uuid(base64):
    BASE64_VALUES = [64] * 123
    BASE64_KEYS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='

    for i, c in enumerate(BASE64_KEYS):
        BASE64_VALUES[ord(c)] = i

    HEX_CHARS = list('0123456789abcdef')
    _template = ['', '', '', '']
    UUID_TEMPLATE = _template + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + ['-'] + _template + _template + _template
    INDICES = [i for i, x in enumerate(UUID_TEMPLATE) if x != '-']
    
    def decode_uuid(base64):
        if len(base64) != 22:
            return base64

        UUID_TEMPLATE[0] = base64[0]
        UUID_TEMPLATE[1] = base64[1]

        j = 2
        for i in range(2, 22, 2):
            lhs = BASE64_VALUES[ord(base64[i])]
            rhs = BASE64_VALUES[ord(base64[i + 1])]
            UUID_TEMPLATE[INDICES[j]] = HEX_CHARS[lhs >> 2]
            UUID_TEMPLATE[INDICES[j + 1]] = HEX_CHARS[((lhs & 3) << 2) | (rhs >> 4)]
            UUID_TEMPLATE[INDICES[j + 2]] = HEX_CHARS[rhs & 0xF]
            j += 3

        return ''.join(UUID_TEMPLATE)

    return decode_uuid(base64)

def chuang_jian_wen_jian_jia(ml):
    if not os.path.exists(ml):
        os.makedirs(ml)

def du_qu_dan_yi_wen_jian_json(wj):
    with open(wj, "r", encoding="utf8") as xa:
        sj = json.load(xa)
    return sj

def dan_zi_jie_xor_shu_ju(sj):
    if sj[:6] == b'encode':
        return bytes([xa ^ sj[6] for xa in sj[7:]])
    else:
        return sj

def zi_yuan_lie_biao_yi(sj):
    zd = {}
    for xa in sj:
        aa = xa.strip().split('\t')
        if len(aa) > 1 and aa[0].endswith('.png'):
            mz = aa[0].split('/')[-1].split('.')[0]
            zd[mz] = f'assets/{aa[1]}'
    return zd

zs = 0
lb = {}

def bao_cun_er_jin_zhi_wen_jian(sj, wj):
    with open(wj, 'wb') as xa:
        xa.write(bytes(sj))

def bao_cun_dan_yi_lie_biao_bian_liang(sj, wj):
    with open(wj, "w", encoding='utf-8') as xa:
        xa.write("\n".join(sj))

def atlas_ti_huan_png_ming_zi(sj, cz, th, wj):
    atl = []
    js = sj.split('\n')
    for xa in js:
        if xa.endswith('.png'):
            aa = xa.replace(cz, th)
        else:
            aa = xa
        atl.append(aa)
    chuang_jian_wen_jian_jia(os.path.dirname(wj))
    bao_cun_dan_yi_lie_biao_bian_liang(atl, wj)

def json_bao_cun_wen_jian(skel, wj):
    chuang_jian_wen_jian_jia(os.path.dirname(wj))
    with open(wj, 'w', encoding='utf-8') as xa:
        json.dump(skel, xa, ensure_ascii=False, separators=(",", ":"))

def ling_zhi_zhan_xian(js):
    global zs, lb
    pd = False
    try:
        sj = json.loads(js.decode('utf-8'))
    except:
        return pd
    if isinstance(sj, list):
        if len(sj) > 5:
            if isinstance(sj[5], list):
                if isinstance(sj[5][0], list):
                    if len(sj[5][0]) > 4:
                        if isinstance(sj[5][0][4], dict):
                            if 'skeleton' in sj[5][0][4]:
                                pd = True
    if pd:
        zs += 1
        cz = sj[5][0][1]
        th = f'{cz}${zs}$a'
        for tda, tdb in enumerate(sj[5][0][3], start=0):
            ym = tdb.replace(cz, th)
            lb[base64_to_uuid(sj[1][tda])] = ym
        atlas_ti_huan_png_ming_zi(sj[5][0][2], cz, th, f'零之战线/{th}.atlas')
        json_bao_cun_wen_jian(sj[5][0][4], f'零之战线/{th}.json')

def ling_zhi_zhan_xian_dao_chu(wj):
    global lb
    with zipfile.ZipFile(wj, 'r') as xa:
        with xa.open('assets/resData') as xb:
            tx = xb.read()
        li = xa.namelist()
        za = zi_yuan_lie_biao_yi(dan_zi_jie_xor_shu_ju(tx).decode('utf-8').split('\n'))
        la = [xc for xc in li if xc.lower().endswith('.json')]
        for xd in la:
            with xa.open(xd) as xe:
                wb = xe.read()
            ling_zhi_zhan_xian(dan_zi_jie_xor_shu_ju(wb))
        for xf, xg in lb.items():
            if xf in za:
                pg = za[xf]
                if pg in li:
                    ml = f'零之战线/{xg}'
                    chuang_jian_wen_jian_jia(os.path.dirname(ml))
                    with xa.open(za[xf]) as xh:
                        pn = xh.read()
                    bao_cun_er_jin_zhi_wen_jian(dan_zi_jie_xor_shu_ju(pn), ml)
                else:
                    print(f'文件并不存在:{xf} {xg}')

ling_zhi_zhan_xian_dao_chu('lzzxgb691_8_5.apk')
</pre>
姬械联盟立绘提取还原名字的代码
因为这玩意名字是没路径的 所以我只能给文件名加个数字后缀，防止覆盖重名
用法的话就是直接改最后一行的ling_zhi_zhan_xian_dao_chu('lzzxgb691_8_5.apk')里的apk名字
我最近搞的游戏 资源都是在apk里的，所以我都直接解析apk导出文件，这样可以不用解压全部文件
效果图如下
![TZD_5LBPSFD1$6Y`3F2RG%2](https://github.com/28598519a/KoK_AssetDecDL/assets/126901037/dc09e5c8-7eb5-4713-8aad-2215a8ab54b7)

**Comment by 2010cxy0** [comment]
大佬，我发现星之守护的h资源似乎不在安装包里，想来是解锁下载的，不知道有没有办法抓取？

**Comment by qiqimutou** [comment]
> 大佬，我发现星之守护的h资源似乎不在安装包里，想来是解锁下载的，不知道有没有办法抓取？

资源就在apk里，贴图格式pvr.ccz 不是png

**Comment by 2010cxy0** [comment]
> > 大佬，我发现星之守护的h资源似乎不在安装包里，想来是解锁下载的，不知道有没有办法抓取？
> 
> 资源就在apk里，贴图格式pvr.ccz 不是png

看到了，非常感谢！
