### ISSUE TITLE
疑似下载出问题

### ISSUE THREAD

**Issue by 2010cxy0** [28598519a/KoK_AssetDecDL#8]
大佬好，这个程序真的非常有用，只是近期发现在获取资源列表后，下载就无法进行了，但是用原本自带的资源列表是可以下载的，想抓一下最新的文件，不知道如何解决，请求帮助！

**Comment by 28598519a** [comment]
檢查過下載列表的連結，結果正常

如果仍然遇到此問題，請提供更詳細的資料包含截圖等
