### ISSUE TITLE
assets_   pcsecret.json 好像不能更新了 更新會報錯

### ISSUE THREAD

**Issue by auntesaunt123** [28598519a/KoK_AssetDecDL#9]
assets_  pcsecret.json 如題 更新了會沒辦法跑  不過這個好像也沒辦法提取  也不是很重要?

另外提一下 Project     QT 好像也有類似要驗證的    SexualDating_4_1 類 就藏著  不過主體有了就很棒了  

能有這方便的工具  非常謝謝您

**Comment by 28598519a** [comment]
Project QT確實有要驗的類，不過我記得是Android才要?

所以我預設是給Web源，而且我記得選Andoird的話我有設會跳警示

**Comment by 28598519a** [comment]
pcsecret我看過了，連結指向沒問題，裡面的內容跟我預設給的格式也相同，不太可能出現報錯
